import './globals.css'
import type { Metadata } from 'next'
import Nav from './(layout)/(nav)/Nav'
import Footer from './(layout)/(footer)/Footer'


export const metadata: Metadata = {
  title: 'Emor Musk Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body>
        <Nav />
        {children}
        <Footer />
        </body>
    </html>
  )
}
