import Container from './main/container/Container'

//THE RESUME SHOULD BE LINKED TO A GOOGLE DOCS CONTAINING YOUR RESUME, BOTH ON NAV AND FOOTER
//CHECK WHY THE INTELLISENSE IS ACTNG UP
//MAKING THE FORM BUTTON DISABLED UNTIL HE INPUTS ARE CORECTLY FILLED

export default function Home() {
  return (
    <Container />
  )
}
